export const EVENT_LOGGED_IN = 'EVENT_LOGGED_IN';
export const EVENT_LOGGED_OUT = 'EVENT_LOGGED_OUT';

export const AUTH_REQUEST_COMPLETE = 'AUTH_REQUEST_COMPLETE';
export const AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR';
export const AUTH_INITIALIZE_REQUEST = 'AUTH_INITIALIZE_REQUEST';
export const AUTH_INITIALIZE_COMPLETE = 'AUTH_INITIALIZE_COMPLETE';
export const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
export const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
export const AUTH_UPDATE_TOKEN_STATE = 'AUTH_UPDATE_TOKEN_STATE';
export const AUTH_REFRESH_ROLES_REQUEST = 'AUTH_REFRESH_ROLES_REQUEST';
export const AUTH_CLEAR_ROLES = 'AUTH_CLEAR_ROLES';
export const AUTH_REFRESH_ROLES_ERROR = 'AUTH_REFRESH_ROLES_ERROR';
export const AUTH_REFRESH_ROLES_COMPLETE = 'AUTH_REFRESH_ROLES_COMPLETE';

export const TEST_GENERATION_LOCK_REQUEST = 'TEST_GENERATION_LOCK_REQUEST';
export const TEST_GENERATION_LOCK_COMPLETE = 'TEST_GENERATION_LOCK_COMPLETE';
export const GENERATION_LOCK_ERROR = 'GENERATION_LOCK_ERROR';
export const ACQUIRE_GENERATION_LOCK_REQUEST = 'ACQUIRE_GENERATION_LOCK_REQUEST';
export const ACQUIRE_GENERATION_LOCK_COMPLETE = 'ACQUIRE_GENERATION_LOCK_COMPLETE';
export const RENEW_GENERATION_LOCK_REQUEST = 'RENEW_GENERATION_LOCK_REQUEST';
export const RENEW_GENERATION_LOCK_COMPLETE = 'RENEW_GENERATION_LOCK_COMPLETE';
export const RELEASE_GENERATION_LOCK_REQUEST = 'RELEASE_GENERATION_LOCK_REQUEST';
export const RELEASE_GENERATION_LOCK_COMPLETE = 'RELEASE_GENERATION_LOCK_COMPLETE';

export const CODE_TABLES_LOAD_REQUEST = 'CODE_TABLES_LOAD_REQUEST';
export const CODE_TABLES_LOAD_REQUEST_COMPLETE = 'CODE_TABLES_LOAD_REQUEST_COMPLETE';
export const CODE_TABLES_LOAD_REQUEST_ERROR = 'CODE_TABLES_LOAD_REQUEST_ERROR';

export const FLASH_MESSAGE_CREATE = 'FLASH_MESSAGE_CREATE';
export const FLASH_MESSAGE_DISMISS = 'FLASH_MESSAGE_DISMISS';
export const FLASH_MESSAGE_TTL_TICK = 'FLASH_MESSAGE_TTL_TICK';

export const EVENT_POLL = 'EVENT_POLL';
export const EVENT_REMOTE_EVENT = 'EVENT_REMOTE_EVENT';

export const WILDLIFE_HEALTH_ID_LOAD_REQUEST = 'WILDLIFE_HEALTH_ID_LOAD_REQUEST';
export const WILDLIFE_HEALTH_ID_LOAD_COMPLETE = 'WILDLIFE_HEALTH_ID_LOAD_COMPLETE';
export const WILDLIFE_HEALTH_ID_LOAD_ERROR = 'WILDLIFE_HEALTH_ID_LOAD_ERROR';
export const WILDLIFE_HEALTH_ID_CLEAR = 'WILDLIFE_HEALTH_ID_CLEAR';
export const WILDLIFE_HEALTH_ID_EDIT_STATE_REQUEST = 'WILDLIFE_HEALTH_ID_EDIT_STATE_REQUEST';
export const WILDLIFE_HEALTH_ID_EDIT_STATE_COMPLETE = 'WILDLIFE_HEALTH_ID_EDIT_STATE_COMPLETE';

export const DEVMODE_SET_STATE = 'DEVMODE_SET_STATE';
