const AUTH_REQUEST_COMPLETE = 'AUTH_REQUEST_COMPLETE';
const AUTH_REQUEST_ERROR = 'AUTH_REQUEST_ERROR';
const AUTH_INITIALIZE_REQUEST = 'AUTH_INITIALIZE_REQUEST';
const AUTH_INITIALIZE_COMPLETE = 'AUTH_INITIALIZE_COMPLETE';
const AUTH_SIGNIN_REQUEST = 'AUTH_SIGNIN_REQUEST';
const AUTH_REFRESH_TOKEN = 'AUTH_REFRESH_TOKEN';
const AUTH_UPDATE_TOKEN_STATE = 'AUTH_UPDATE_TOKEN_STATE';

export {
  AUTH_REFRESH_TOKEN,
  AUTH_UPDATE_TOKEN_STATE,
  AUTH_SIGNIN_REQUEST,
  AUTH_INITIALIZE_REQUEST,
  AUTH_INITIALIZE_COMPLETE,
  AUTH_REQUEST_COMPLETE,
  AUTH_REQUEST_ERROR
};
