---
kind: Template
apiVersion: v1
metadata:
  name: "${NAME}-deployment-template"
  creationTimestamp: 
objects:
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    annotations:
      description: Defines how to deploy ${NAME}
  spec:
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${NAME}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: "${SOURCE_IMAGE_NAME}:${TAG_NAME}"
    replicas: 1
    selector:
      name: "${NAME}"
    template:
      metadata:
        name: "${NAME}"
        labels:
          name: ${NAME}
          app: ${APP_GROUP}
          app-group: ${APP_GROUP}
      spec:
        containers:
        - name: "${NAME}"
          image: ''
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: NODE_ENV
            value: production
          - name: whis_SESSION_SALT
            value: "${whis_SESSION_SALT}"
          - name: BASE_URL
            value: /
          - name: whis_API_HOST
            value: whis-api
          - name: whis_API_PORT
            value: '8080'
          - name: KEYCLOAK_CLIENT_ID
            value: "${KEYCLOAK_CLIENT_ID}"
          - name: KEYCLOAK_REALM
            value: "${KEYCLOAK_REALM}"
          - name: KEYCLOAK_SERVER_URL
            value: "${KEYCLOAK_SERVER_URL}"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${NAME}"
    labels:
      name: ${NAME}
      app: ${APP_GROUP}
      app-group: ${APP_GROUP}
    annotations:
      description: Exposes and load balances the application pods.
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: "${NAME}"
    type: ClusterIP
    sessionAffinity: None

parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: whis-ui
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: whis
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: whis-ui 
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The namespace of the OpenShift project containing the imagestream for the application.
  required: true
  value: 0dff19-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of CPU the container can use.
  value: 10m
- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of CPU the container can use.
  value: 500m
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
- name: whis_SESSION_SALT
  displayName: whis_SESSION_SALT
  description: Used to bind with Keycloak
  value: CHANGEME
- name: KEYCLOAK_CLIENT_ID
  displayName: KEYCLOAK_CLIENT_ID
  description: Used to bind with Keycloak
  value: CHANGEME
- name: KEYCLOAK_REALM
  displayName: KEYCLOAK_REALM
  description: Used to bind with Keycloak
  value: CHANGEME
- name: KEYCLOAK_SERVER_URL
  displayName: KEYCLOAK_SERVER_URL
  description: Used to bind with Keycloak
  value: CHANGEME