kind: Service
apiVersion: v1
metadata:
  name: whis-ui
  labels:
    app: whis-ui
    env: dev
spec:
  ports:
    - name: web-frontend
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: whis-ui
